name: API tests

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
       include:
         - lemurro_version: "2.0"
           sql_file: "database.sql"
         - lemurro_version: "2.1"
           sql_file: "database.my.sql"

    env:
      LEMURRO_VERSION: ${{ matrix.lemurro_version }}
      PROJ_FOLDER: /home/runner/work/api-core/api-core/testproject
      CONFIGS_FOLDER: /home/runner/work/api-core/api-core/testproject/api/app/Overrides/Configs
      APP_TESTS_FOLDER: /home/runner/work/api-core/api-core/testproject/api/tests
      CORE_TESTS_FOLDER: /home/runner/work/api-core/api-core/testproject/api/vendor/lemurro/api-core/tests

    steps:
      - uses: actions/checkout@v2

      - name: "Test"
        run: |
          composer --version
          php -v
