name: API tests

on:
  push:
    branches: [ master, v1.10 ]

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        include:
          - lemurro_version: "1.10"
            sql_file: "database.sql"
            php_version: "7.4"
            operating-system: ubuntu-20.04

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set environment variables"
        run: |
          echo "PROJ_FOLDER=$GITHUB_WORKSPACE/testproject" >> $GITHUB_ENV
          echo "CONFIGS_FOLDER=$GITHUB_WORKSPACE/testproject/api/app/Configs" >> $GITHUB_ENV
          echo "APP_TESTS_FOLDER=$GITHUB_WORKSPACE/testproject/api/tests" >> $GITHUB_ENV
          echo "CORE_TESTS_FOLDER=$GITHUB_WORKSPACE/testproject/api/vendor/lemurro/api-core/tests" >> $GITHUB_ENV

      - name: "Test"
        run: |
          mkdir $PROJ_FOLDER
          touch $PROJ_FOLDER/php.ini
          echo -e "log_errors = Off\n;error_log = php_errors.log\n" > $PROJ_FOLDER/php.ini
          sed -i 's/log_errors = Off/log_errors = On/g' $PROJ_FOLDER/php.ini
          sed -i "s|;error_log = php_errors.log|error_log = $PROJ_FOLDER/php_errors.log|g" $PROJ_FOLDER/php.ini
          cat $PROJ_FOLDER/php.ini
