name: API tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    env:
      PROJ_FOLDER: /home/runner/work/ghactions_test/ghactions_test/testproject
      CONFIGS_FOLDER: /home/runner/work/ghactions_test/ghactions_test/testproject/api/app/Overrides/Configs

    steps:
    - uses: actions/checkout@v2

    - name: Start MySQL
      run: sudo systemctl start mysql.service

    - name: Install Lemurro
      run: |
        composer global require --no-progress --no-scripts --no-plugins lemurro/installer
        sed -i 's/setTty(true)/setTty(false)/g' ~/.composer/vendor/lemurro/installer/src/NewCommand.php
        ~/.composer/vendor/bin/lemurro new testproject --lv=2.0 --api --skip --silent
        composer install --working-dir=$PROJ_FOLDER/api/vendor/lemurro/api-core

    - name: Prepare database
      run: |
        touch ~/.my.cnf
        echo -e "[mysql]\nuser=root\npassword=root\n" > ~/.my.cnf
        mysql -h 127.0.0.1 --execute="CREATE DATABASE lemurro"
        mysql -h 127.0.0.1 lemurro < $PROJ_FOLDER/api/database.sql
        mysql -h 127.0.0.1 --execute="SELECT * FROM lemurro.users"

    - name: "Configuration: file.yaml"
      run: |
        touch $CONFIGS_FOLDER/file.yaml
        echo -e "file:\n  path_logs: $PROJ_FOLDER/api/var/logs\n  path_temp: /home/runner/work/ghactions_test/ghactions_test/testproject/api/var/temp\n  path_upload: /home/runner/work/ghactions_test/ghactions_test/testproject/api/var/documents" > $CONFIGS_FOLDER/file.yaml
        cat $CONFIGS_FOLDER/file.yaml

    - name: "Configuration: guides.yaml"
      run: |
        touch $CONFIGS_FOLDER/guides.yaml
        echo -e "guides:\n  classes:\n    example: Example" > $CONFIGS_FOLDER/guides.yaml
        cat $CONFIGS_FOLDER/guides.yaml

    - name: "Configuration: [app]api.suite.yml"
      run: |
        cp $PROJ_FOLDER/api/tests/api.suite.dist.yml $PROJ_FOLDER/api/tests/api.suite.yml
        sed -i 's/lemurro\-api\.localhost/localhost\:8000/g' $PROJ_FOLDER/api/tests/api.suite.yml
        cat $PROJ_FOLDER/api/tests/api.suite.yml

    - name: "Configuration: [core]api.suite.yml"
      run: |
        cp $PROJ_FOLDER/api/vendor/lemurro/api-core/tests/api.suite.dist.yml $PROJ_FOLDER/api/vendor/lemurro/api-core/tests/api.suite.yml
        sed -i 's/lemurro\-api\.localhost/localhost\:8000/g' $PROJ_FOLDER/api/vendor/lemurro/api-core/tests/api.suite.yml
        cat $PROJ_FOLDER/api/vendor/lemurro/api-core/tests/api.suite.yml

    - name: "Running web server"
      run: php -S localhost:8000 -t $PROJ_FOLDER/api/public

# ~/.composer
# ~/work/ghactions_test/ghactions_test
# ~/work/ghactions_test/ghactions_test/testproject


#      - run:
#          name: "Tests: app"
#          command: |
#            cd /home/runner/work/ghactions_test/ghactions_test/testproject/api
#            php vendor/bin/codecept run api
#      - run:
#          name: "Tests: core"
#          command: |
#            cd /home/runner/work/ghactions_test/ghactions_test/testproject/api/vendor/lemurro/api-core
#            php vendor/bin/codecept run api
