name: API tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Start MySQL
      run: sudo systemctl start mysql.service

    - name: Install Lemurro
      run: |
        composer global require --no-progress --no-scripts --no-plugins lemurro/installer
        sed -i 's/setTty(true)/setTty(false)/g' ~/.composer/vendor/lemurro/installer/src/NewCommand.php
        ~/.composer/vendor/bin/lemurro new testproject --lv=2.0 --api --skip --silent
        composer install --working-dir=/home/runner/work/ghactions_test/ghactions_test/testproject/api/vendor/lemurro/api-core

    - name: Prepare database
      run: |
        touch ~/.my.cnf
        echo -e "[mysql]\nuser=root\npassword=root\n" > ~/.my.cnf
        mysql -h 127.0.0.1 --execute="CREATE DATABASE lemurro"
        mysql -h 127.0.0.1 lemurro < ~/work/ghactions_test/ghactions_test/testproject/api/database.sql
        mysql -h 127.0.0.1 --execute="SELECT * FROM lemurro.users"

    - name: "Configuration: file.yaml"
      working-directory: /home/circleci/project/testproject/api/app/Overrides/Configs
      run: |
        touch ./file.yaml
        echo -e "file:\n  path_logs: /home/circleci/project/testproject/api/var/logs\n  path_temp: /home/circleci/project/testproject/api/var/temp\n  path_upload: /home/circleci/project/testproject/api/var/documents" > ./file.yaml
        cat ./file.yaml
    - name: "Configuration: guides.yaml"
      working-directory: /home/circleci/project/testproject/api/app/Overrides/Configs
      run: |
        touch ./guides.yaml
        echo -e "guides:\n  classes:\n    example: Example" > ./guides.yaml
        cat ./guides.yaml
    - name: "Configuration: [app]api.suite.yml"
      working-directory: /home/circleci/project/testproject/api/tests
      run: |
        cp ./api.suite.dist.yml ./api.suite.yml
        sed -i 's/lemurro\-api\.localhost/localhost\:8000/g' ./api.suite.yml
        cat ./api.suite.yml
    - name: "Configuration: [core]api.suite.yml"
      working-directory: /home/circleci/project/testproject/api/vendor/lemurro/api-core/tests
      run: |
        cp ./api.suite.dist.yml ./api.suite.yml
        sed -i 's/lemurro\-api\.localhost/localhost\:8000/g' ./api.suite.yml
        cat ./api.suite.yml

# ~/.composer
# ~/work/ghactions_test/ghactions_test
# ~/work/ghactions_test/ghactions_test/testproject

#      - run:
#          name: "Running web server"
#          command: php -S localhost:8000 -t /home/circleci/project/testproject/api/public
#          background: true
#      - run:
#          name: "Tests: app"
#          command: |
#            cd /home/circleci/project/testproject/api
#            php vendor/bin/codecept run api
#      - run:
#          name: "Tests: core"
#          command: |
#            cd /home/circleci/project/testproject/api/vendor/lemurro/api-core
#            php vendor/bin/codecept run api
