name: API tests

on:
  push:
    branches: [ master, v1.10 ]

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        include:
          - lemurro_version: "1.10"
            sql_file: "database.sql"
            php_version: "7.4"
            operating-system: ubuntu-20.04

    env:
      PROJ_FOLDER: /home/runner/work/ghactions_test/ghactions_test/testproject
      CONFIGS_FOLDER: /home/runner/work/ghactions_test/ghactions_test/testproject/api/app/Configs
      APP_TESTS_FOLDER: /home/runner/work/ghactions_test/ghactions_test/testproject/api/tests
      CORE_TESTS_FOLDER: /home/runner/work/ghactions_test/ghactions_test/testproject/api/vendor/lemurro/api-core/tests

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Start MySQL"
        run: sudo systemctl start mysql.service

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}

      - name: "Versions"
        run: |
          lsb_release -a
          mysql -V
          php -v

      - name: "PHP"
        run: |
          cp /etc/php/7.4/cli/php.ini $GITHUB_WORKSPACE/php.ini
          sed -i 's/log_errors = Off/log_errors = On/g' $GITHUB_WORKSPACE/php.ini
          sed -i "s/;error_log = php_errors.log/error_log = $GITHUB_WORKSPACE\/php_errors.log/g" $GITHUB_WORKSPACE/php.ini
          cat $GITHUB_WORKSPACE/php.ini
          #sudo echo -e "error_log=/var/log/php_errors.log\n" > /etc/php/7.4/cli/conf.d/my_php.ini
          
          
          
          
          
          
          
          
          
          
          
