name: API tests

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
       include:
         - lemurro_version: "2.0"
           php_version: "7.4"
           sql_file: "database.sql"
         - lemurro_version: "2.1"
           php_version: "7.4"
           sql_file: "database.my.sql"

    env:
      LEMURRO_VERSION: ${{ matrix.lemurro_version }}
      PROJ_FOLDER: /home/runner/work/api-core/api-core/testproject
      CONFIGS_FOLDER: /home/runner/work/api-core/api-core/testproject/api/app/Overrides/Configs
      APP_TESTS_FOLDER: /home/runner/work/api-core/api-core/testproject/api/tests
      CORE_TESTS_FOLDER: /home/runner/work/api-core/api-core/testproject/api/vendor/lemurro/api-core/tests

    steps:
      - uses: actions/checkout@v2

      - name: "Start MySQL"
        run: sudo systemctl start mysql.service

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
#          extensions: xdebug-beta

      - name: "Install Lemurro"
        run: |
          composer global require --no-progress --no-scripts --no-plugins lemurro/installer "^2.1"
          sed -i 's/setTty(true)/setTty(false)/g' ~/.composer/vendor/lemurro/installer/src/NewCommand.php
          ~/.composer/vendor/bin/lemurro new testproject --lv=$LEMURRO_VERSION --api --skip --silent
#          composer install --working-dir=$PROJ_FOLDER/api/vendor/lemurro/api-core
